name: HuePlugin
main: se.fredsfursten.hueplugin.HuePlugin
version: 0.1-DEV
author: vanbrayne
description: A Minecraft plugin for controlling Philips Hue lamps, based on events on a minecraft server
commands:
  hue:
    description: Control the behaviour
    usage: /hue on | off
    permission-message: You don't have <permission>
permissions:
  hue.*:
    description: Gives access to all donationboard commands
    default: op
    donationboard.on: true
    donationboard.off: true
  hue.on:
    description: Access to /hue on
    default: op
  hue.off:
    description: Access to /hue off
    default: op
